# Generated by Django 5.1.4 on 2025-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name="手机号"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "管理员"), ("editor", "编辑"), ("user", "普通用户")],
                default="user",
                max_length=10,
                verbose_name="用户类型",
            ),
        ),
    ]
