# Generated by Django 5.1.4 on 2025-01-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0002_alter_user_phone_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="custom_auth_user",
        ),
    ]
