# Generated by Django 5.1.4 on 2025-01-23 16:03

import custom_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0003_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", custom_auth.models.AsyncUserManager()),
            ],
        ),
    ]
