# Generated by Django 5.1.4 on 2025-01-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.CharField(max_length=255, unique=True, verbose_name="原文链接"),
        ),
    ]
