# Generated by Django 5.1.4 on 2025-01-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_newsarticle_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticle",
            old_name="url",
            new_name="source_url",
        ),
    ]
