# Generated by Django 5.1.4 on 2025-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_auto_20250121_2003"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlerconfig",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="是否激活"),
        ),
        migrations.AddField(
            model_name="crawlertask",
            name="is_test",
            field=models.BooleanField(default=False, verbose_name="是否测试任务"),
        ),
        migrations.AddIndex(
            model_name="crawlerconfig",
            index=models.Index(fields=["is_active", "-updated_at"], name="crawler_cra_is_acti_e79da7_idx"),
        ),
        migrations.AddIndex(
            model_name="crawlertask",
            index=models.Index(fields=["is_test", "-start_time"], name="crawler_cra_is_test_35b1db_idx"),
        ),
    ]
