# Generated by Django 5.1.4 on 2025-01-24 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0004_add_initial_crawler_configs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlertask",
            name="task_id",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name="任务ID"),
        ),
    ]
