# Generated by Django 5.1.4 on 2025-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0005_modify_task_id_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlerconfig",
            name="max_retries",
            field=models.IntegerField(default=3, verbose_name="最大重试次数"),
        ),
        migrations.AddField(
            model_name="crawlerconfig",
            name="retry_delay",
            field=models.IntegerField(default=60, verbose_name="重试延迟(秒)"),
        ),
    ]
