# Generated by Django 5.1.4 on 2025-01-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keyword", models.CharField(max_length=100, unique=True, verbose_name="关键词")),
                ("search_count", models.IntegerField(default=0, verbose_name="搜索次数")),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热门")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "搜索建议",
                "verbose_name_plural": "搜索建议",
                "ordering": ["-search_count", "-updated_at"],
                "indexes": [
                    models.Index(fields=["-search_count"], name="news_search_search__e51234_idx"),
                    models.Index(fields=["keyword"], name="news_search_keyword_eb550f_idx"),
                ],
            },
        ),
    ]
