# Generated by Django 5.1.4 on 2025-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="duration",
            field=models.IntegerField(
                default=300, help_text="指标超过阈值持续n分钟后触发告警", verbose_name="持续时间(秒)"
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("cpu_usage", "CPU使用率"),
                    ("memory_usage", "内存使用率"),
                    ("disk_usage", "磁盘使用率"),
                    ("network_in", "网络入流量"),
                    ("network_out", "网络出流量"),
                ],
                max_length=20,
                verbose_name="监控指标",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="layout_type",
            field=models.CharField(
                choices=[("grid", "网格布局"), ("flex", "弹性布局"), ("fixed", "固定布局")],
                default="grid",
                max_length=20,
                verbose_name="布局类型",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringvisualization",
            name="chart_type",
            field=models.CharField(
                choices=[("line", "折线图"), ("bar", "柱状图"), ("gauge", "仪表盘"), ("pie", "饼图")],
                max_length=20,
                verbose_name="图表类型",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringvisualization",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="monitoringvisualization",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("cpu_usage", "CPU使用率"),
                    ("memory_usage", "内存使用率"),
                    ("disk_usage", "磁盘使用率"),
                    ("network_in", "网络入流量"),
                    ("network_out", "网络出流量"),
                ],
                max_length=20,
                verbose_name="指标类型",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringvisualization",
            name="refresh_interval",
            field=models.IntegerField(default=300, help_text="数据自动刷新的间隔", verbose_name="刷新间隔(秒)"),
        ),
        migrations.AlterField(
            model_name="systemmetrics",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("cpu_usage", "CPU使用率"),
                    ("memory_usage", "内存使用率"),
                    ("disk_usage", "磁盘使用率"),
                    ("network_in", "网络入流量"),
                    ("network_out", "网络出流量"),
                ],
                max_length=20,
                verbose_name="指标类型",
            ),
        ),
    ]
