# Generated by Django 5.1.4 on 2025-01-17 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="config",
            field=models.JSONField(default=dict, verbose_name="配置"),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="是否默认"),
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.CharField(max_length=20, verbose_name="日志级别")),
                ("message", models.TextField(verbose_name="错误信息")),
                ("stack_trace", models.TextField(blank=True, null=True, verbose_name="堆栈跟踪")),
                ("source", models.CharField(max_length=100, verbose_name="错误来源")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="创建者"
                    ),
                ),
            ],
            options={
                "verbose_name": "错误日志",
                "verbose_name_plural": "错误日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
