# Generated by Django 5.1.4 on 2025-01-18 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_dashboard_config_alter_dashboard_is_default_errorlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboard",
            options={"ordering": ["-created_at"], "verbose_name": "仪表盘", "verbose_name_plural": "仪表盘"},
        ),
        migrations.AlterModelOptions(
            name="dashboardwidget",
            options={
                "ordering": ["dashboard", "created_at"],
                "verbose_name": "仪表盘小部件",
                "verbose_name_plural": "仪表盘小部件",
            },
        ),
        migrations.RemoveIndex(
            model_name="alertnotificationconfig",
            name="monitoring__user_id_f5e0a3_idx",
        ),
        migrations.RemoveIndex(
            model_name="alertnotificationconfig",
            name="monitoring__created_2bf7cd_idx",
        ),
        migrations.RemoveIndex(
            model_name="dashboard",
            name="monitoring__created_d86c59_idx",
        ),
        migrations.RemoveIndex(
            model_name="dashboardwidget",
            name="monitoring__dashboa_6f7e96_idx",
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="config",
        ),
        migrations.AddField(
            model_name="alertnotificationconfig",
            name="last_notified",
            field=models.DateTimeField(blank=True, null=True, verbose_name="上次通知时间"),
        ),
        migrations.AddField(
            model_name="alertnotificationconfig",
            name="notification_count",
            field=models.IntegerField(default=0, verbose_name="通知次数"),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="layout",
            field=models.JSONField(default=dict, verbose_name="布局配置"),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="visualization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="monitoring.monitoringvisualization",
                verbose_name="可视化配置",
            ),
        ),
        migrations.AlterField(
            model_name="alertnotificationconfig",
            name="alert_levels",
            field=models.JSONField(help_text="接收哪些级别的告警", verbose_name="告警级别"),
        ),
        migrations.AlterField(
            model_name="alertnotificationconfig",
            name="config",
            field=models.JSONField(help_text="通知相关的配置信息", verbose_name="通知配置"),
        ),
        migrations.AlterField(
            model_name="alertnotificationconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="alertnotificationconfig",
            name="name",
            field=models.CharField(max_length=100, verbose_name="通知名称"),
        ),
        migrations.AlterField(
            model_name="alertnotificationconfig",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("email", "邮件通知"),
                    ("sms", "短信通知"),
                    ("webhook", "Webhook通知"),
                    ("dingtalk", "钉钉通知"),
                    ("wechat", "微信通知"),
                ],
                max_length=20,
                verbose_name="通知类型",
            ),
        ),
        migrations.AlterField(
            model_name="alertnotificationconfig",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="description",
            field=models.TextField(blank=True, verbose_name="仪表盘描述"),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="layout_type",
            field=models.CharField(
                choices=[("grid", "网格布局"), ("flex", "弹性布局"), ("free", "自由布局")],
                default="grid",
                max_length=20,
                verbose_name="布局类型",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="name",
            field=models.CharField(max_length=100, verbose_name="仪表盘名称"),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="config",
            field=models.JSONField(default=dict, verbose_name="配置信息"),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="monitoring.dashboard",
                verbose_name="所属仪表盘",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="是否可见"),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="name",
            field=models.CharField(max_length=100, verbose_name="小部件名称"),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="position",
            field=models.JSONField(default=dict, verbose_name="位置信息"),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="widget_type",
            field=models.CharField(
                choices=[("chart", "图表"), ("metric", "指标"), ("text", "文本"), ("alert", "告警")],
                default="chart",
                max_length=20,
                verbose_name="小部件类型",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(fields=["created_by", "is_default"], name="monitoring__created_578ec7_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(fields=["created_at"], name="monitoring__created_81e130_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(fields=["dashboard", "is_visible"], name="monitoring__dashboa_c4a3b4_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(fields=["created_at"], name="monitoring__created_c1b3a0_idx"),
        ),
    ]
