# Generated by Django 5.1.5 on 2025-02-03 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_alter_alerthistory_message_alter_alerthistory_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="errorlog",
            name="error_log_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="errorlog",
            name="error_log_severity_idx",
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="error_message",
            field=models.TextField(verbose_name="错误消息"),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="error_type",
            field=models.CharField(
                choices=[
                    ("system", "系统错误"),
                    ("application", "应用错误"),
                    ("database", "数据库错误"),
                    ("network", "网络错误"),
                    ("security", "安全错误"),
                    ("other", "其他错误"),
                ],
                max_length=20,
                verbose_name="错误类型",
            ),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="severity",
            field=models.CharField(
                choices=[("info", "信息"), ("warning", "警告"), ("error", "错误"), ("critical", "严重")],
                max_length=20,
                verbose_name="严重程度",
            ),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="source",
            field=models.CharField(max_length=255, verbose_name="错误来源"),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(fields=["error_type", "severity"], name="monitoring__error_t_1017dd_idx"),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(fields=["created_at"], name="monitoring__created_49ec08_idx"),
        ),
    ]
