# Generated by Django 5.1.5 on 2025-02-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_remove_errorlog_error_log_created_at_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemmetrics",
            options={"ordering": ["-created_at"], "verbose_name": "系统指标", "verbose_name_plural": "系统指标"},
        ),
        migrations.RemoveIndex(
            model_name="systemmetrics",
            name="monitoring__metric__641d8a_idx",
        ),
        migrations.RenameField(
            model_name="systemmetrics",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddIndex(
            model_name="systemmetrics",
            index=models.Index(fields=["metric_type", "created_at"], name="monitoring__metric__57191f_idx"),
        ),
    ]
