# Generated by Django 5.1.4 on 2025-01-20 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_alerthistory_created_by_systemmetrics_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="systemmetrics",
            name="monitoring__metric__5bdd21_idx",
        ),
        migrations.AlterField(
            model_name="systemmetrics",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_metrics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AlterField(
            model_name="systemmetrics",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
        ),
        migrations.AddIndex(
            model_name="systemmetrics",
            index=models.Index(fields=["metric_type", "timestamp"], name="monitoring__metric__641d8a_idx"),
        ),
        migrations.AddIndex(
            model_name="systemmetrics",
            index=models.Index(fields=["created_by"], name="monitoring__created_ad5770_idx"),
        ),
    ]
