# Generated by Django 5.1.4 on 2025-01-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_rename_is_active_alertrule_is_enabled'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE monitoring_errorlog SET level = severity WHERE level IS NULL;
            ALTER TABLE monitoring_errorlog DROP COLUMN severity;
            ALTER TABLE monitoring_errorlog CHANGE COLUMN level severity VARCHAR(20);
            """,
            reverse_sql="""
            ALTER TABLE monitoring_errorlog CHANGE COLUMN severity level VARCHAR(20);
            """
        ),
    ]
