site_name: MediaSense
site_description: 新闻舆情监控系统
site_author: MediaSense Team
repo_url: https://github.com/mediasense/mediasense-backend
repo_name: mediasense-backend

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    primary: blue
    accent: blue

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 首页: index.md
  - 开发文档:
    - 后端开发计划: backend-development-plan.md
    - 新闻开发文档: news-Development-Documentation.md
    - 新闻需求文档: news-requirements.md
  - API文档:
    - 认证API: api/auth.md
    - 新闻API: api/news.md
    - 搜索API: api/search.md
    - 爬虫API: api/crawler.md
    - AI服务API: api/ai.md
    - 监控API: api/monitor.md
  - 部署文档:
    - 环境配置: deploy/environment.md
    - 数据库配置: deploy/database.md
    - 服务配置: deploy/services.md
    - Docker部署: deploy/docker.md
  - 测试文档:
    - 单元测试: test/unit.md
    - 集成测试: test/integration.md
    - 性能测试: test/performance.md 