# Generated by Django 5.1.4 on 2025-01-13 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrule",
            name="is_active",
            field=models.IntegerField(default=1, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="analysisschedule",
            name="is_active",
            field=models.IntegerField(default=1, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="analysisvisualization",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="analysisvisualization",
            name="is_active",
            field=models.IntegerField(default=1, verbose_name="是否启用"),
        ),
    ]
