# Generated by Django 5.1.4 on 2025-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0002_alter_analysisrule_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchanalysistask",
            options={"verbose_name": "批量分析任务", "verbose_name_plural": "批量分析任务"},
        ),
        migrations.RemoveField(
            model_name="batchanalysistask",
            name="analysis_types",
        ),
        migrations.RemoveField(
            model_name="batchanalysistask",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="batchanalysistask",
            name="news_ids",
        ),
        migrations.RemoveField(
            model_name="batchanalysistask",
            name="processed_articles",
        ),
        migrations.RemoveField(
            model_name="batchanalysistask",
            name="started_at",
        ),
        migrations.RemoveField(
            model_name="batchanalysistask",
            name="success_articles",
        ),
        migrations.RemoveField(
            model_name="batchanalysistask",
            name="total_articles",
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="failed",
            field=models.IntegerField(default=0, verbose_name="失败数"),
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="processed",
            field=models.IntegerField(default=0, verbose_name="已处理"),
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="success",
            field=models.IntegerField(default=0, verbose_name="成功数"),
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="total_count",
            field=models.IntegerField(default=0, verbose_name="总数"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="错误信息"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="status",
            field=models.CharField(
                choices=[("pending", "等待中"), ("processing", "处理中"), ("completed", "已完成"), ("failed", "失败")],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterModelTable(
            name="batchanalysistask",
            table="ai_service_batchanalysistask",
        ),
    ]
