# Generated by Django 5.1.4 on 2025-01-23 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0003_alter_batchanalysistask_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchanalysistask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "批量分析任务",
                "verbose_name_plural": "批量分析任务",
            },
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="config",
            field=models.JSONField(
                default=dict, help_text="包含news_ids和analysis_types等配置", verbose_name="配置信息"
            ),
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_batch_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="name",
            field=models.CharField(default="批量分析任务", max_length=100, verbose_name="任务名称"),
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_tasks",
                to="ai_service.analysisrule",
                verbose_name="分析规则",
            ),
        ),
        migrations.AddField(
            model_name="batchanalysistask",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="failed",
            field=models.IntegerField(default=0, verbose_name="失败数量"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="processed",
            field=models.IntegerField(default=0, verbose_name="已处理数量"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="success",
            field=models.IntegerField(default=0, verbose_name="成功数量"),
        ),
        migrations.AlterField(
            model_name="batchanalysistask",
            name="total_count",
            field=models.IntegerField(default=0, verbose_name="总数量"),
        ),
        migrations.AddIndex(
            model_name="batchanalysistask",
            index=models.Index(fields=["status"], name="ai_service__status_118356_idx"),
        ),
        migrations.AddIndex(
            model_name="batchanalysistask",
            index=models.Index(fields=["created_at"], name="ai_service__created_2cb155_idx"),
        ),
        migrations.AddIndex(
            model_name="batchanalysistask",
            index=models.Index(fields=["rule"], name="ai_service__rule_id_54fee8_idx"),
        ),
        migrations.AlterModelTable(
            name="batchanalysistask",
            table=None,
        ),
    ]
